// Real Muslim Influencers API Data
export const realInfluencers = [
  {
    id: "real-danzy-001",
    full_name: "Danzy",
    user_type: "creator",
    avatar_url: "/uploads/avatars/danzy-profile.jpg",
    bio: "Daily Islamic content creator sharing authentic Islamic knowledge. NOT A SHEIKH ⚠️ Just sharing what I learn.",
    location: "United Kingdom",
    verified: true,
    email_verified: true,
    creator_profiles: [
      {
        niche: "Islamic Education",
        languages: ["English", "Arabic"],
        platforms: {
          tiktok: {
            handle: "its_danzy",
            followers: 2800000,
            engagement_rate: 8.5,
            url: "https://www.tiktok.com/@its_danzy",
          },
          instagram: {
            handle: "its_danzy",
            followers: 450000,
            engagement_rate: 6.2,
            url: "https://www.instagram.com/its_danzy/",
          },
          youtube: {
            handle: "DanzyHD108",
            subscribers: 180000,
            engagement_rate: 7.8,
            url: "https://www.youtube.com/@DanzyHD108",
          },
        },
        pricing: {
          tiktok_video: 2500,
          instagram_post: 1800,
          instagram_story: 800,
          youtube_video: 5000,
          package_deal: 8000,
        },
        rating: 4.9,
        total_reviews: 23,
        halal_certified: true,
        total_campaigns: 12,
        profile_views: 15600,
      },
    ],
  },
  {
    id: "real-sana-ayaana-001",
    full_name: "Sana & Ayaana",
    user_type: "creator",
    avatar_url: "/uploads/avatars/sana-ayaana-profile.jpg",
    bio: "Muslim lifestyle content creators sharing modest fashion, family life, and Islamic values. Inspiring Muslim women worldwide 🌙",
    location: "United States",
    verified: true,
    email_verified: true,
    creator_profiles: [
      {
        niche: "Modest Fashion & Lifestyle",
        languages: ["English", "Urdu"],
        platforms: {
          instagram: {
            handle: "sana_and_ayaana",
            followers: 320000,
            engagement_rate: 7.2,
            url: "https://www.instagram.com/sana_and_ayaana/",
          },
          tiktok: {
            handle: "sana_and_ayaana",
            followers: 180000,
            engagement_rate: 9.1,
            url: "https://www.tiktok.com/@sana_and_ayaana",
          },
        },
        pricing: {
          instagram_post: 2200,
          instagram_story: 900,
          tiktok_video: 1800,
          reel: 2500,
          package_deal: 6500,
        },
        rating: 4.8,
        total_reviews: 31,
        halal_certified: true,
        total_campaigns: 18,
        profile_views: 12400,
      },
    ],
  },
  {
    id: "real-geeky-girl-001",
    full_name: "Geeky Girl in USA",
    user_type: "creator",
    avatar_url: "/uploads/avatars/geeky-girl-profile.jpg",
    bio: "Muslim tech enthusiast sharing hijabi life in tech, modest fashion, and empowering Muslim women in STEM 👩‍💻🧕",
    location: "United States",
    verified: true,
    email_verified: true,
    creator_profiles: [
      {
        niche: "Tech & Modest Fashion",
        languages: ["English"],
        platforms: {
          instagram: {
            handle: "geekygirlinusa",
            followers: 95000,
            engagement_rate: 8.9,
            url: "https://www.instagram.com/geekygirlinusa/",
          },
          tiktok: {
            handle: "geekygirlinusa",
            followers: 140000,
            engagement_rate: 11.2,
            url: "https://www.tiktok.com/@geekygirlinusa",
          },
        },
        pricing: {
          instagram_post: 1200,
          instagram_story: 500,
          tiktok_video: 1000,
          tech_review: 2500,
          package_deal: 3500,
        },
        rating: 4.7,
        total_reviews: 19,
        halal_certified: true,
        total_campaigns: 14,
        profile_views: 8900,
      },
    ],
  },
  {
    id: "real-sana-howais-001",
    full_name: "Sana Howais",
    user_type: "creator",
    avatar_url: "/uploads/avatars/sana-howais-profile.jpg",
    bio: "Muslim lifestyle blogger sharing authentic Islamic content, modest fashion, and inspiring Muslim women to live their best halal life 🌙✨",
    location: "Canada",
    verified: true,
    email_verified: true,
    creator_profiles: [
      {
        niche: "Islamic Lifestyle & Fashion",
        languages: ["English", "Arabic"],
        platforms: {
          instagram: {
            handle: "sanahowais.official",
            followers: 210000,
            engagement_rate: 6.8,
            url: "https://www.instagram.com/sanahowais.official/",
          },
          youtube: {
            handle: "SanaHowais",
            subscribers: 85000,
            engagement_rate: 8.2,
            url: "https://www.youtube.com/@SanaHowais",
          },
        },
        pricing: {
          instagram_post: 1800,
          instagram_story: 700,
          youtube_video: 3500,
          sponsored_post: 2500,
          package_deal: 5500,
        },
        rating: 4.6,
        total_reviews: 27,
        halal_certified: true,
        total_campaigns: 16,
        profile_views: 11200,
      },
    ],
  },
  {
    id: "real-sally-shahine-001",
    full_name: "Sally Shahine",
    user_type: "creator",
    avatar_url: "/uploads/avatars/sally-shahine-profile.jpg",
    bio: "Muslim content creator sharing beauty, modest fashion, and lifestyle content. Empowering Muslim women to feel confident and beautiful 💄🧕",
    location: "United States",
    verified: true,
    email_verified: true,
    creator_profiles: [
      {
        niche: "Beauty & Modest Fashion",
        languages: ["English", "Arabic"],
        platforms: {
          instagram: {
            handle: "sallyshahine_official",
            followers: 165000,
            engagement_rate: 7.5,
            url: "https://www.instagram.com/sallyshahine_official/",
          },
          tiktok: {
            handle: "sallyshahine",
            followers: 220000,
            engagement_rate: 10.3,
            url: "https://www.tiktok.com/@sallyshahine",
          },
        },
        pricing: {
          instagram_post: 1500,
          instagram_story: 600,
          tiktok_video: 1300,
          beauty_tutorial: 2000,
          package_deal: 4200,
        },
        rating: 4.8,
        total_reviews: 22,
        halal_certified: true,
        total_campaigns: 13,
        profile_views: 9800,
      },
    ],
  },
]

export const realCampaigns = [
  {
    id: "real-campaign-001",
    title: "Ramadan Islamic Content Series",
    description:
      "Looking for authentic Muslim creators to share meaningful Ramadan content that educates and inspires the Muslim community",
    category: "Islamic Education",
    campaign_type: ["TikTok Video", "Instagram Post"],
    budget_min: 2000,
    budget_max: 5000,
    target_audience: ["Muslim Community", "Young Muslims (18-35)", "Islamic Education Seekers"],
    requirements: "Must be practicing Muslim, authentic content only, no controversial topics",
    deliverables: ["3 TikTok videos", "2 Instagram posts", "Story highlights"],
    status: "active",
    applications_count: 8,
    brand: {
      id: "real-danzy-001",
      full_name: "Danzy",
      avatar_url: "/uploads/avatars/danzy-profile.jpg",
    },
  },
  {
    id: "real-campaign-002",
    title: "Modest Fashion Summer Collection",
    description: "Showcase our new modest summer collection with authentic Muslim lifestyle content",
    category: "Modest Fashion",
    campaign_type: ["Instagram Post", "Instagram Reel"],
    budget_min: 1500,
    budget_max: 3500,
    target_audience: ["Muslim Women (20-40)", "Modest Fashion Enthusiasts", "Family-oriented Muslims"],
    requirements: "Family-friendly content, modest styling, authentic representation",
    deliverables: ["2 Instagram posts", "1 Instagram reel", "3 story posts"],
    status: "active",
    applications_count: 12,
    brand: {
      id: "real-sana-ayaana-001",
      full_name: "Sana & Ayaana",
      avatar_url: "/uploads/avatars/sana-ayaana-profile.jpg",
    },
  },
]
